services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 350rln34y9g85
      MYSQL_DATABASE: tienda_maquillaje_db_development
      MYSQL_USER: userproy
      MYSQL_PASSWORD: 350rln34y9g85
    volumes:
      - db_data:/var/lib/mysql
      - ./Backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    deploy:
      resources:
        limits:
          memory: 2g   # súbelo si tienes RAM
        reservations:
          memory: 1g

  backend:
    build:
      context: ./Backend
    container_name: rails_app
    volumes:
      - ./Backend:/app
    ports:
      - "4000:4000"
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USERNAME: userproy
      DATABASE_PASSWORD: 350rln34y9g85
      DATABASE_NAME: tienda_maquillaje_db_development
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 2g   # súbelo si tienes RAM
        reservations:
          memory: 1g

  frontend:
    build:
      context: ./FrontendReact/ale-beauty-react
      dockerfile: Dockerfile.dev
    container_name: react_app
    command: npm run dev
    volumes:
      - ./FrontendReact/ale-beauty-react:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 2g   # súbelo si tienes RAM
        reservations:
          memory: 1g

  dashboard:
      build:
        context: ./Dashboard/ale-beauty-dashboard
        dockerfile: Dockerfile.dev
      container_name: dashboard_app
      command: npm run dev -- --host
      volumes:
        - ./Dashboard/ale-beauty-dashboard:/app
        - /app/node_modules
      ports:
        - "5173:5173"
      stdin_open: true
      tty: true
      depends_on:
        - backend
      deploy:
        resources:
          limits:
            memory: 2g   # súbelo si tienes RAM
          reservations:
            memory: 1g

volumes:
  db_data:
